name: CoreFitnessApp

options:
  bundleIdPrefix: com.kzm
  deploymentTarget:
    iOS: 16.0
  usesSwiftPackages: true
  localizations:
    - ja
    - en

settings:
  base:
    MARKETING_VERSION: 1.0.0
    CURRENT_PROJECT_VERSION: 1
    CODE_SIGN_STYLE: Automatic
    TARGETED_DEVICE_FAMILY: "1,2"
    SWIFT_VERSION: 5.0

  configs:
    Debug:
      DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
      SWIFT_OPTIMIZATION_LEVEL: -Onone
    Release:
      SWIFT_OPTIMIZATION_LEVEL: -O
      SWIFT_COMPILATION_MODE: wholemodule

packages:
  ComposableArchitecture:
    url: https://github.com/pointfreeco/swift-composable-architecture
    exactVersion: 1.6.0

targets:
  CoreFitness:
    type: application
    platform: iOS
    sources:
      - CoreFitness
    resources:
      - CoreFitness/Resources

    settings:
      base:
        PRODUCT_NAME: "CoreFitness"
        PRODUCT_BUNDLE_IDENTIFIER: com.kzm.CoreFitness
        INFOPLIST_FILE: CoreFitness/Supports/Info.plist
        CODE_SIGN_STYLE: Automatic
        UILaunchStoryboardName: LaunchScreen
        UIRequiresFullScreen: true
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UIStatusBarHidden: false
        UIStatusBarStyle: UIStatusBarStyleLightContent

    dependencies:
      - package: ComposableArchitecture
        product: ComposableArchitecture

    preBuildScripts:
      - name: SwiftLint
        runOnlyWhenInstalling: false
        path: scripts/swiftlint.sh
        shell: /bin/sh
      - name: SwiftFormat
        runOnlyWhenInstalling: false
        path: scripts/swiftformat.sh
        shell: /bin/sh

schemes:
  CoreFitness:
    build:
      targets:
        CoreFitness: all
    run:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
